// welcome.js
export const WELCOME_MENU_STATE = 'WELCOME_MENU_STATE'
export const UPDATE_WELCOME_MENU_STATE = 'UPDATE_WELCOME_MENU_STATE'
export const WELCOME_ALL_STATE = 'WELCOME_ALL_STATE'
export const UPDATE_WELCOME_ALL_STATE = 'UPDATE_WELCOME_ALL_STATE'
